-- 011_order_timeline.sql
-- Order Timeline: per-event change tracking for orders

CREATE TABLE IF NOT EXISTS order_timeline (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  actor_name TEXT,
  actor_phone TEXT,
  actor_id TEXT,
  old_value JSONB,
  new_value JSONB,
  change_details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_timeline_order_id ON order_timeline(order_id);
CREATE INDEX IF NOT EXISTS idx_order_timeline_created_at ON order_timeline(created_at);

-- Allow authenticated inserts via anon key
ALTER TABLE order_timeline ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'order_timeline' AND policyname = 'order_timeline_insert_anon'
  ) THEN
    CREATE POLICY order_timeline_insert_anon ON order_timeline
      FOR INSERT TO anon
      WITH CHECK (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'order_timeline' AND policyname = 'order_timeline_select_anon'
  ) THEN
    CREATE POLICY order_timeline_select_anon ON order_timeline
      FOR SELECT TO anon
      USING (true);
  END IF;
END
$$;
